# Generated by Django 2.0.6 on 2019-02-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='data',
            new_name='date',
        ),
    ]
